[package]
name = "pancakes"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
futures = "0.3.32"
iced = {version = "0.14.0", features = ["tokio", "debug"]}
reqwest = "0.13.2"
serde_json = "1.0.149"
tokio = {version = "1.49", features = ["full"]}
